name: Deploy Lambda using Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.8.5

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Package Lambda code
      run: |
        cd lambda_function
        zip -r ../terraform/lambda.zip ./*
        cd ..

    - name: Initialize Terraform
      working-directory: ./terraform
      run: terraform init

    - name: Plan Infrastructure
      working-directory: ./terraform
      run: terraform plan

    - name: Apply Infrastructure
      working-directory: ./terraform
      run: terraform apply -auto-approve
